"""add_subject_model

Revision ID: 492e8611d87c
Revises: 4ffd91f4a519
Create Date: 2026-07-10 02:20:34.045515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492e8611d87c'
down_revision: Union[str, Sequence[str], None] = '4ffd91f4a519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.Enum('THEORY', 'LABORATORY', name='subjecttype'), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('faculty_name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_code'), 'subject', ['code'], unique=False)
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_index(op.f('ix_subject_semester_id'), 'subject', ['semester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_semester_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_code'), table_name='subject')
    op.drop_table('subject')
    # ### end Alembic commands ###
