"""add_assessment_models

Revision ID: 6ade1cef9f90
Revises: 492e8611d87c
Create Date: 2026-07-10 02:32:34.211700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ade1cef9f90'
down_revision: Union[str, Sequence[str], None] = '492e8611d87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', sa.Enum('ASSIGNMENT', 'QUIZ', 'SURPRISE_TEST', 'PRE_END', 'END_SEMESTER', name='assessmenttype'), nullable=False),
    sa.Column('assessment_category', sa.Enum('THEORY', 'LABORATORY', name='assessmentcategory'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('weightage', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('conducted_on', sa.Date(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_id'), 'assessment', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_subject_id'), 'assessment', ['subject_id'], unique=False)
    op.create_table('assessment_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'CHECKED', name='assessmentstatus'), nullable=False),
    sa.Column('obtained_marks', sa.Integer(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_result_assessment_id'), 'assessment_result', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_assessment_result_id'), 'assessment_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_result_id'), table_name='assessment_result')
    op.drop_index(op.f('ix_assessment_result_assessment_id'), table_name='assessment_result')
    op.drop_table('assessment_result')
    op.drop_index(op.f('ix_assessment_subject_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_id'), table_name='assessment')
    op.drop_table('assessment')
    # ### end Alembic commands ###
