"""Make updated_at non-nullable for subject and assessment

Revision ID: 78f92f97e167
Revises: 3dce2d399688
Create Date: 2026-07-10 15:22:30.919322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f92f97e167'
down_revision: Union[str, Sequence[str], None] = '3dce2d399688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE assessment SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('assessment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.execute("UPDATE assessment_result SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('assessment_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.execute("UPDATE subject SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('subject', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('assessment_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('assessment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
